CREATE TYPE "public"."julia_artifact_kind" AS ENUM('structure', 'json', 'fasta', 'log', 'text', 'other');--> statement-breakpoint
CREATE TYPE "public"."julia_run_event_type" AS ENUM('queued', 'running', 'tool_started', 'tool_completed', 'message', 'artifact_created', 'completed', 'run_error');--> statement-breakpoint
CREATE TYPE "public"."julia_run_mode" AS ENUM('chat', 'research');--> statement-breakpoint
CREATE TYPE "public"."julia_run_status" AS ENUM('queued', 'running', 'completed', 'failed', 'canceled');--> statement-breakpoint
CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "julia_artifacts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project_id" uuid NOT NULL,
	"run_id" uuid,
	"kind" "julia_artifact_kind" DEFAULT 'other' NOT NULL,
	"filename" text NOT NULL,
	"content_type" text,
	"r2_key" text NOT NULL,
	"size_bytes" integer,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "julia_context_references" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project_id" uuid NOT NULL,
	"thread_id" uuid,
	"message_id" uuid,
	"artifact_id" uuid,
	"label" text NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "julia_messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"thread_id" uuid NOT NULL,
	"role" text NOT NULL,
	"content" text NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "julia_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "julia_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text,
	"created_by_id" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "julia_projects" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_id" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "julia_run_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"run_id" uuid NOT NULL,
	"type" "julia_run_event_type" NOT NULL,
	"message" text,
	"sequence" integer DEFAULT 0 NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "julia_runs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project_id" uuid NOT NULL,
	"thread_id" uuid,
	"mode" "julia_run_mode" DEFAULT 'chat' NOT NULL,
	"status" "julia_run_status" DEFAULT 'queued' NOT NULL,
	"input" text,
	"summary" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "julia_threads" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project_id" uuid NOT NULL,
	"title" text NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "julia_artifacts" ADD CONSTRAINT "julia_artifacts_project_id_julia_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."julia_projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "julia_artifacts" ADD CONSTRAINT "julia_artifacts_run_id_julia_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."julia_runs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "julia_context_references" ADD CONSTRAINT "julia_context_references_project_id_julia_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."julia_projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "julia_context_references" ADD CONSTRAINT "julia_context_references_thread_id_julia_threads_id_fk" FOREIGN KEY ("thread_id") REFERENCES "public"."julia_threads"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "julia_context_references" ADD CONSTRAINT "julia_context_references_message_id_julia_messages_id_fk" FOREIGN KEY ("message_id") REFERENCES "public"."julia_messages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "julia_context_references" ADD CONSTRAINT "julia_context_references_artifact_id_julia_artifacts_id_fk" FOREIGN KEY ("artifact_id") REFERENCES "public"."julia_artifacts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "julia_messages" ADD CONSTRAINT "julia_messages_thread_id_julia_threads_id_fk" FOREIGN KEY ("thread_id") REFERENCES "public"."julia_threads"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "julia_post" ADD CONSTRAINT "julia_post_created_by_id_user_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "julia_projects" ADD CONSTRAINT "julia_projects_owner_id_user_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "julia_run_events" ADD CONSTRAINT "julia_run_events_run_id_julia_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."julia_runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "julia_runs" ADD CONSTRAINT "julia_runs_project_id_julia_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."julia_projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "julia_runs" ADD CONSTRAINT "julia_runs_thread_id_julia_threads_id_fk" FOREIGN KEY ("thread_id") REFERENCES "public"."julia_threads"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "julia_threads" ADD CONSTRAINT "julia_threads_project_id_julia_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."julia_projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "julia_artifacts_project_id_idx" ON "julia_artifacts" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "julia_artifacts_run_id_idx" ON "julia_artifacts" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX "julia_artifacts_kind_idx" ON "julia_artifacts" USING btree ("kind");--> statement-breakpoint
CREATE INDEX "julia_context_references_project_id_idx" ON "julia_context_references" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "julia_context_references_thread_id_idx" ON "julia_context_references" USING btree ("thread_id");--> statement-breakpoint
CREATE INDEX "julia_context_references_artifact_id_idx" ON "julia_context_references" USING btree ("artifact_id");--> statement-breakpoint
CREATE INDEX "julia_messages_thread_id_idx" ON "julia_messages" USING btree ("thread_id");--> statement-breakpoint
CREATE INDEX "julia_post_created_by_idx" ON "julia_post" USING btree ("created_by_id");--> statement-breakpoint
CREATE INDEX "julia_post_name_idx" ON "julia_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "julia_projects_owner_id_idx" ON "julia_projects" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX "julia_run_events_run_id_idx" ON "julia_run_events" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX "julia_run_events_type_idx" ON "julia_run_events" USING btree ("type");--> statement-breakpoint
CREATE INDEX "julia_runs_project_id_idx" ON "julia_runs" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "julia_runs_thread_id_idx" ON "julia_runs" USING btree ("thread_id");--> statement-breakpoint
CREATE INDEX "julia_runs_status_idx" ON "julia_runs" USING btree ("status");--> statement-breakpoint
CREATE INDEX "julia_threads_project_id_idx" ON "julia_threads" USING btree ("project_id");