CREATE TYPE "public"."autopep_artifact_storage_kind" AS ENUM('neon', 'modal_volume', 'external_url');--> statement-breakpoint
CREATE TYPE "public"."autopep_artifact_type" AS ENUM('pdb', 'mmcif', 'literature_summary', 'search_report', 'proteina_input', 'log', 'other');--> statement-breakpoint
CREATE TYPE "public"."autopep_event_level" AS ENUM('debug', 'info', 'warn', 'error');--> statement-breakpoint
CREATE TYPE "public"."autopep_literature_source" AS ENUM('pubmed', 'pmc', 'biorxiv', 'medrxiv', 'other');--> statement-breakpoint
CREATE TYPE "public"."autopep_project_status" AS ENUM('active', 'archived');--> statement-breakpoint
CREATE TYPE "public"."autopep_run_phase" AS ENUM('intake', 'entity_normalization', 'pdb_search', 'literature_search', 'ranking', 'pdb_download', 'artifact_sync', 'ready_for_complexa', 'failed');--> statement-breakpoint
CREATE TYPE "public"."autopep_run_status" AS ENUM('queued', 'running', 'succeeded', 'failed', 'canceled');--> statement-breakpoint
CREATE TYPE "public"."autopep_workspace_status" AS ENUM('cold', 'ready', 'running', 'failed');--> statement-breakpoint
CREATE TABLE "autopep_project" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(256) NOT NULL,
	"objective" text NOT NULL,
	"target_description" text,
	"status" "autopep_project_status" DEFAULT 'active' NOT NULL,
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "autopep_project_workspace" (
	"project_id" uuid PRIMARY KEY NOT NULL,
	"modal_app_name" text DEFAULT 'autopep-discovery-agent' NOT NULL,
	"modal_volume_name" text NOT NULL,
	"volume_root" text NOT NULL,
	"active_sandbox_id" text,
	"active_sandbox_name" text,
	"filesystem_snapshot_image_id" text,
	"status" "autopep_workspace_status" DEFAULT 'cold' NOT NULL,
	"last_synced_at" timestamp with time zone,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "autopep_agent_run" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project_id" uuid NOT NULL,
	"objective" text NOT NULL,
	"status" "autopep_run_status" DEFAULT 'queued' NOT NULL,
	"phase" "autopep_run_phase" DEFAULT 'intake' NOT NULL,
	"model" text DEFAULT 'gpt-5.5' NOT NULL,
	"harness_name" text DEFAULT 'codex' NOT NULL,
	"life_science_plugin_ref" text NOT NULL,
	"top_k" integer DEFAULT 5 NOT NULL,
	"modal_sandbox_id" text,
	"modal_sandbox_name" text,
	"modal_filesystem_snapshot_image_id" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"error_message" text,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "autopep_agent_event" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "autopep_agent_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"run_id" uuid NOT NULL,
	"sequence" integer NOT NULL,
	"phase" "autopep_run_phase",
	"level" "autopep_event_level" DEFAULT 'info' NOT NULL,
	"type" text NOT NULL,
	"message" text NOT NULL,
	"payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "autopep_protein_candidate" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project_id" uuid NOT NULL,
	"run_id" uuid NOT NULL,
	"rank" integer NOT NULL,
	"pdb_id" text,
	"chain_ids" text[] DEFAULT '{}' NOT NULL,
	"title" text NOT NULL,
	"source_database" text DEFAULT 'RCSB PDB' NOT NULL,
	"source_url" text,
	"organism" text,
	"experimental_method" text,
	"resolution_angstrom" double precision,
	"relevance_score" double precision,
	"selection_rationale" text NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "autopep_artifact" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project_id" uuid NOT NULL,
	"run_id" uuid,
	"protein_candidate_id" uuid,
	"type" "autopep_artifact_type" NOT NULL,
	"storage_kind" "autopep_artifact_storage_kind" NOT NULL,
	"display_name" text NOT NULL,
	"mime_type" text,
	"content_text" text,
	"content_sha256" text,
	"size_bytes" integer,
	"modal_volume_name" text,
	"modal_path" text,
	"external_url" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "autopep_literature_hit" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project_id" uuid NOT NULL,
	"run_id" uuid NOT NULL,
	"source" "autopep_literature_source" NOT NULL,
	"title" text NOT NULL,
	"abstract" text,
	"doi" text,
	"pmid" text,
	"pmcid" text,
	"url" text,
	"published_at" timestamp with time zone,
	"relevance_score" double precision,
	"summary" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "autopep_project" ADD CONSTRAINT "autopep_project_createdById_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "autopep_project_workspace" ADD CONSTRAINT "autopep_project_workspace_project_id_autopep_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."autopep_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "autopep_agent_run" ADD CONSTRAINT "autopep_agent_run_project_id_autopep_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."autopep_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "autopep_agent_event" ADD CONSTRAINT "autopep_agent_event_run_id_autopep_agent_run_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."autopep_agent_run"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "autopep_protein_candidate" ADD CONSTRAINT "autopep_protein_candidate_project_id_autopep_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."autopep_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "autopep_protein_candidate" ADD CONSTRAINT "autopep_protein_candidate_run_id_autopep_agent_run_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."autopep_agent_run"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "autopep_artifact" ADD CONSTRAINT "autopep_artifact_project_id_autopep_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."autopep_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "autopep_artifact" ADD CONSTRAINT "autopep_artifact_run_id_autopep_agent_run_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."autopep_agent_run"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "autopep_artifact" ADD CONSTRAINT "autopep_artifact_protein_candidate_id_autopep_protein_candidate_id_fk" FOREIGN KEY ("protein_candidate_id") REFERENCES "public"."autopep_protein_candidate"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "autopep_literature_hit" ADD CONSTRAINT "autopep_literature_hit_project_id_autopep_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."autopep_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "autopep_literature_hit" ADD CONSTRAINT "autopep_literature_hit_run_id_autopep_agent_run_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."autopep_agent_run"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "autopep_project_created_by_idx" ON "autopep_project" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "autopep_project_status_idx" ON "autopep_project" USING btree ("status");--> statement-breakpoint
CREATE INDEX "autopep_project_workspace_status_idx" ON "autopep_project_workspace" USING btree ("status");--> statement-breakpoint
CREATE INDEX "autopep_project_workspace_volume_name_idx" ON "autopep_project_workspace" USING btree ("modal_volume_name");--> statement-breakpoint
CREATE INDEX "autopep_agent_run_project_idx" ON "autopep_agent_run" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "autopep_agent_run_status_idx" ON "autopep_agent_run" USING btree ("status");--> statement-breakpoint
CREATE INDEX "autopep_agent_run_phase_idx" ON "autopep_agent_run" USING btree ("phase");--> statement-breakpoint
CREATE INDEX "autopep_agent_event_run_idx" ON "autopep_agent_event" USING btree ("run_id");--> statement-breakpoint
CREATE UNIQUE INDEX "autopep_agent_event_run_sequence_idx" ON "autopep_agent_event" USING btree ("run_id","sequence");--> statement-breakpoint
CREATE INDEX "autopep_protein_candidate_project_idx" ON "autopep_protein_candidate" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "autopep_protein_candidate_run_idx" ON "autopep_protein_candidate" USING btree ("run_id");--> statement-breakpoint
CREATE UNIQUE INDEX "autopep_protein_candidate_run_rank_idx" ON "autopep_protein_candidate" USING btree ("run_id","rank");--> statement-breakpoint
CREATE INDEX "autopep_artifact_project_idx" ON "autopep_artifact" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "autopep_artifact_run_idx" ON "autopep_artifact" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX "autopep_artifact_candidate_idx" ON "autopep_artifact" USING btree ("protein_candidate_id");--> statement-breakpoint
CREATE INDEX "autopep_artifact_type_idx" ON "autopep_artifact" USING btree ("type");--> statement-breakpoint
CREATE INDEX "autopep_artifact_content_sha_idx" ON "autopep_artifact" USING btree ("content_sha256");--> statement-breakpoint
CREATE INDEX "autopep_literature_hit_project_idx" ON "autopep_literature_hit" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "autopep_literature_hit_run_idx" ON "autopep_literature_hit" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX "autopep_literature_hit_source_idx" ON "autopep_literature_hit" USING btree ("source");
